### PR TITLE
Optimize 2.5.7 Circle Pyramid.py

### PR DESCRIPTION
**Pull request by ItsFireninja**
I optimized 2.5.7 as I added functions and for loops to make it in less lines

### CODE REVIEW

**Comment by aditeyapatakoti** [comment]
I didn't use functions and for loops because they aren't introduced into the course yet. (I think) They should've been introduced later on but correct me if i'm wrong. 

Note: I might add a file of your code for this assignment as a variant of my code.

**Review by aditeyapatakoti — COMMENTED** [review]
I didn't use functions and for loops because they aren't introduced into the course yet. (I think) They should've been introduced later on but correct me if i'm wrong.

Note: I might add a file of your code for this assignment as a variant of my code.

**Comment by ItsFireninja** [comment]
For loops were there but functions weren't but you can just replace everywhere with my function with this code:
pendown()
circle(50)
penup()

**Comment by ItsFireninja** [comment]
Fixed the code to remove functions

**Comment by aditeyapatakoti** [comment]
Did you edit both files to make them not have functions in them, only for loops? Let me know once you have done that so I can merge the pull request.

**Comment by ItsFireninja** [comment]
Yeah I edited both files to not have functions in them

**Pull request merged**
